name: Copy folder
description: Copy the contents of one folder to another folder
inputs:
  source-folder:
    description: Path to the source folder
    required: true
  destination-folder:
    description: Destination folder
    required: true
  delete-extra:
    description: Delete destination files that are not present in the source folder
    required: false
    default: 'false'
  exclude-file:
    description: Optional exclusion list
    required: false
    default: ''
runs:
  using: node24
  main: index.js
